dist: bionic
language: python
addons:
 apt:
   packages:
   - gcc
matrix:
  include:
    - language: python
      python: '3.6'
      env: TOXENV=py36-flake8

    - language: python
      python: '3.7'
      env: TOXENV=py37-flake8

    - language: python
      python: '3.8'
      env: TOXENV=py38-flake8

install:
  - pip install tox
script:
  - tox -v
